<img src="https://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

# Python for Finance (2nd ed.)

**Mastering Data-Driven Finance**

&copy; Dr. Yves J. Hilpisch | The Python Quants GmbH

<img src="https://hilpisch.com/images/py4fi_2nd_shadow.png" width="300px" align="left">

# Object Oriented Programming

## Introduction

In [1]:
class HumanBeing(object):  
    def __init__(self, first_name, eye_color):  
        self.first_name = first_name  
        self.eye_color = eye_color  
        self.position = 0  
    def walk_steps(self, steps):  
        self.position += steps  

In [2]:
Sandra = HumanBeing('Sandra', 'blue')  

In [3]:
Sandra.first_name  

'Sandra'

In [4]:
Sandra.position  

0

In [5]:
Sandra.walk_steps(5)  

In [6]:
Sandra.position  

5

## A Brief Look at Standard Objects

### int

In [7]:
n = 5  

In [8]:
type(n)  

int

In [9]:
n.numerator  

5

In [10]:
n.bit_length()  

3

In [11]:
n + n  

10

In [12]:
2 * n  

10

In [13]:
n.__sizeof__()  

28

### list

In [14]:
l = [1, 2, 3, 4]  

In [15]:
type(l)  

list

In [16]:
l[0]  

1

In [17]:
l.append(10)  

In [18]:
l + l  

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [19]:
2 * l  

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [20]:
sum(l)  

20

In [21]:
l.__sizeof__()  

104

### ndarray

In [22]:
import numpy as np  

In [23]:
a = np.arange(16).reshape((4, 4))  

In [24]:
a  

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
type(a)  

numpy.ndarray

In [26]:
a.nbytes  

128

In [27]:
a.sum()  

np.int64(120)

In [28]:
a.cumsum(axis=0)  

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

In [29]:
a + a  

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [30]:
2 * a  

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [31]:
sum(a)  

array([24, 28, 32, 36])

In [32]:
np.sum(a)  

np.int64(120)

In [33]:
a.__sizeof__()  

128

### DataFrame

In [34]:
import pandas as pd  

In [35]:
df = pd.DataFrame(a, columns=list('abcd'))  

In [36]:
type(df)  

pandas.core.frame.DataFrame

In [37]:
df.columns  

Index(['a', 'b', 'c', 'd'], dtype='object')

In [38]:
df.sum()  

a    24
b    28
c    32
d    36
dtype: int64

In [39]:
df.cumsum()  

a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [40]:
df + df  

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [41]:
2 * df  

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [42]:
np.sum(df, axis=0)  

a    24
b    28
c    32
d    36
dtype: int64

In [43]:
df.__sizeof__()  

260

## Basics of Python Classes

In [44]:
class FinancialInstrument(object):  
    pass  

In [45]:
fi = FinancialInstrument()  

In [46]:
type(fi)  

__main__.FinancialInstrument

In [47]:
fi  

In [48]:
fi.__str__()  

'<__main__.FinancialInstrument object at 0x107562630>'

In [49]:
fi.price = 100  

In [50]:
fi.price  

100

In [51]:
class FinancialInstrument(object):
    author = 'Yves Hilpisch'  
    def __init__(self, symbol, price):  
        self.symbol = symbol  
        self.price = price  

In [52]:
FinancialInstrument.author  

'Yves Hilpisch'

In [53]:
aapl = FinancialInstrument('AAPL', 100)  

In [54]:
aapl.symbol  

'AAPL'

In [55]:
aapl.author  

'Yves Hilpisch'

In [56]:
aapl.price = 105  

In [57]:
aapl.price  

105

In [58]:
class FinancialInstrument(FinancialInstrument):  
    def get_price(self):  
        return self.price  
    def set_price(self, price):  
        self.price = price  

In [59]:
fi = FinancialInstrument('AAPL', 100)  

In [60]:
fi.get_price()  

100

In [61]:
fi.set_price(105)  

In [62]:
fi.get_price()  

105

In [63]:
fi.price  

105

In [64]:
class FinancialInstrument(object):
    def __init__(self, symbol, price):
        self.symbol = symbol  
        self.__price = price  
    def get_price(self):
        return self.__price
    def set_price(self, price):
        self.__price = price

In [65]:
fi = FinancialInstrument('AAPL', 100)

In [66]:
fi.get_price()  

100

In [67]:
# causes intentional error
# fi.__price  

In [68]:
fi._FinancialInstrument__price  

100

In [69]:
fi._FinancialInstrument__price = 105  

In [70]:
fi.set_price(100)  

In [71]:
class PortfolioPosition(object):
    def __init__(self, financial_instrument, position_size):
        self.position = financial_instrument  
        self.__position_size = position_size  
    def get_position_size(self):
        return self.__position_size
    def update_position_size(self, position_size):
        self.__position_size = position_size
    def get_position_value(self):
        return self.__position_size * \
               self.position.get_price()  

In [72]:
pp = PortfolioPosition(fi, 10)

In [73]:
pp.get_position_size()

10

In [74]:
pp.get_position_value()  

1000

In [75]:
pp.position.get_price()  

100

In [76]:
pp.position.set_price(105)  

In [77]:
pp.get_position_value()  

1050

## Python Data Model

In [78]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):  
        self.x = x  
        self.y = y  
        self.z = z  

In [79]:
v = Vector(1, 2, 3)  

In [80]:
v  

In [81]:
class Vector(Vector):
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)

In [82]:
v = Vector(1, 2, 3)

In [83]:
v  

Vector(1, 2, 3)

In [84]:
print(v)  

Vector(1, 2, 3)


In [85]:
class Vector(Vector):
    def __abs__(self):
        return (self.x ** 2 +  self.y ** 2 +
                self.z ** 2) ** 0.5  
    
    def __bool__(self):
        return bool(abs(self))

In [86]:
v = Vector(1, 2, -1)  

In [87]:
abs(v)

2.449489742783178

In [88]:
bool(v)

True

In [89]:
v = Vector()  

In [90]:
v  

Vector(0, 0, 0)

In [91]:
abs(v)

0.0

In [92]:
bool(v)

False

In [93]:
class Vector(Vector):
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)  
    
    def __mul__(self, scalar):
        return Vector(self.x * scalar,
                      self.y * scalar,
                      self.z * scalar)  

In [94]:
v = Vector(1, 2, 3)

In [95]:
v + Vector(2, 3, 4)

Vector(3, 5, 7)

In [96]:
v * 2

Vector(2, 4, 6)

In [97]:
class Vector(Vector):
    def __len__(self):
        return 3  
    
    def __getitem__(self, i):
        if i in [0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')

In [98]:
v = Vector(1, 2, 3)

In [99]:
len(v)

3

In [100]:
v[0]

1

In [101]:
v[-2]

2

In [102]:
# causes intentional error
# v[3]

In [103]:
class Vector(Vector):
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

In [104]:
v = Vector(1, 2, 3)

In [105]:
for i in range(3):  
    print(v[i])  

1
2
3


In [106]:
for coordinate in v:  
    print(coordinate)  

1
2
3


In [107]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):
        self.x = x
        self.y = y
        self.z = z
    
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)
    
    def __abs__(self):
        return (self.x ** 2 +  self.y ** 2 + self.z ** 2) ** 0.5
    
    def __bool__(self):
        return bool(abs(self))
    
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)
    
    def __mul__(self, scalar):
        return Vector(self.x * scalar,
                      self.y * scalar,
                      self.z * scalar)
    
    def __len__(self):
        return 3
    
    def __getitem__(self, i):
        if i in [0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')
            
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

<img src="https://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

<a href="https://tpq.io" target="_blank">https://tpq.io</a> | <a href="https://twitter.com/dyjh" target="_blank">@dyjh</a> | <a href="mailto:training@tpq.io">training@tpq.io</a>