<img src="https://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

# Python for Finance (2nd ed.)

**Mastering Data-Driven Finance**

&copy; Dr. Yves J. Hilpisch | The Python Quants GmbH

<img src="https://hilpisch.com/images/py4fi_2nd_shadow.png" width="300px" align="left">

# Numerical Computing with NumPy

## Arrays with Python Lists

In [1]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]  

In [2]:
m = [v, v, v]  
m  

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [3]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [4]:
m[1][0]

0.5

In [5]:
v1 = [0.5, 1.5]
v2 = [1, 2]
m = [v1, v2]
c = [m, m]  
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [6]:
c[1][1][0]

1

In [7]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [8]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [9]:
from copy import deepcopy
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 * [deepcopy(v), ]  
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [10]:
v[0] = 'Python'  
m  

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

## Interlude: Python Array Class

In [11]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [12]:
import array

In [13]:
a = array.array('f', v)  
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [14]:
a.append(0.5)  
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [15]:
a.extend([5.0, 6.75])  
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [16]:
2 * a  

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [17]:
# causes intentional error
# a.append('string')  

In [18]:
a.tolist()  

[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75]

In [19]:
f = open('array.apy', 'wb')  
a.tofile(f)  
f.close()  

In [20]:
with open('array.apy', 'wb') as f:  
    a.tofile(f)  

In [21]:
!ls -n arr*  

-rw-r--r--  1 501  20  32  4 Jun 11:29 array.apy


In [22]:
b = array.array('f')  

In [23]:
with open('array.apy', 'rb') as f:  
    b.fromfile(f, 5)  

In [24]:
b  

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [25]:
b = array.array('d')  

In [26]:
with open('array.apy', 'rb') as f:
    b.fromfile(f, 2)  

In [27]:
b  

array('d', [0.0004882813645963324, 0.12500002956949174])

## Regular NumPy Arrays

### The Basics

In [28]:
import numpy as np  

In [29]:
a = np.array([0, 0.5, 1.0, 1.5, 2.0])  
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [30]:
type(a)  

numpy.ndarray

In [31]:
a = np.array(['a', 'b', 'c'])  
a

array(['a', 'b', 'c'], dtype='<U1')

In [32]:
a = np.arange(2, 20, 2)  
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
a = np.arange(8, dtype=float)  
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [34]:
a[5:]  

array([5., 6., 7.])

In [35]:
a[:2]  

array([0., 1.])

In [36]:
a.sum()  

np.float64(28.0)

In [37]:
a.std()  

np.float64(2.29128784747792)

In [38]:
a.cumsum()  

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [39]:
l = [0., 0.5, 1.5, 3., 5.]
2 * l  

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [40]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [41]:
2 * a  

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [42]:
a ** 2  

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [43]:
2 ** a  

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [44]:
a ** a  

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [45]:
np.exp(a)  

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [46]:
np.sqrt(a)  

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [47]:
np.sqrt(2.5)  

np.float64(1.5811388300841898)

In [48]:
import math  

In [49]:
math.sqrt(2.5)  

1.5811388300841898

In [50]:
# causes intentional error
# math.sqrt(a)  

In [51]:
%timeit np.sqrt(2.5)  

415 ns ± 6.54 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [52]:
%timeit math.sqrt(2.5)  

24.7 ns ± 0.883 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


### Multiple Dimensions

In [53]:
b = np.array([a, a * 2])  
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [54]:
b[0]  

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [55]:
b[0, 2]  

np.float64(2.0)

In [56]:
b[:, 1]  

array([1., 2.])

In [57]:
b.sum()  

np.float64(84.0)

In [58]:
b.sum(axis=0)  

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [59]:
b.sum(axis=1)  

array([28., 56.])

In [60]:
c = np.zeros((2, 3), dtype='i', order='C')  
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [61]:
c = np.ones((2, 3, 4), dtype='i', order='C')  
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [62]:
d = np.zeros_like(c, dtype=np.float16, order='C')  
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float16)

In [63]:
d = np.ones_like(c, dtype=np.float16, order='C')  
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float16)

In [64]:
e = np.empty((2, 3, 2))  
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [65]:
f = np.empty_like(c)  
f

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [66]:
np.eye(5)  

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
g = np.linspace(5, 15, 12) 
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

### Meta-Information

In [68]:
g.size  

12

In [69]:
g.itemsize  

8

In [70]:
g.ndim  

1

In [71]:
g.shape  

(12,)

In [72]:
g.dtype  

dtype('float64')

In [73]:
g.nbytes  

96

### Reshaping, Resizing, Stacking, Flattening

In [74]:
g = np.arange(15)

In [75]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
g.shape  

(15,)

In [77]:
np.shape(g) 

(15,)

In [78]:
g.reshape((3, 5))  

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
h = g.reshape((5, 3))  
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [80]:
h.T  

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [81]:
h.transpose()  

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [82]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [83]:
np.resize(g, (3, 1))  

array([[0],
       [1],
       [2]])

In [84]:
np.resize(g, (1, 5))  

array([[0, 1, 2, 3, 4]])

In [85]:
np.resize(g, (2, 5))  

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
n = np.resize(g, (5, 4))  
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

In [87]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [88]:
np.hstack((h, 2 * h))  

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [89]:
np.vstack((h, 0.5 * h))  

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [90]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [91]:
h.flatten()  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
h.flatten(order='C')  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [93]:
h.flatten(order='F')  

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [94]:
for i in h.flat:  
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [95]:
for i in h.ravel(order='C'):  
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [96]:
for i in h.ravel(order='F'):  
    print(i, end=',')

0,3,6,9,12,1,4,7,10,13,2,5,8,11,14,

### Boolean Arrays

In [97]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [98]:
h > 8  

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [99]:
h <= 7  

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [100]:
h == 5  

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [101]:
(h == 5).astype(int)  

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [102]:
(h > 4) & (h <= 12)  

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [103]:
h[h > 8]  

array([ 9, 10, 11, 12, 13, 14])

In [104]:
h[(h > 4) & (h <= 12)]  

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [105]:
h[(h < 4) | (h >= 12)]  

array([ 0,  1,  2,  3, 12, 13, 14])

In [106]:
np.where(h > 7, 1, 0)  

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [107]:
np.where(h % 2 == 0, 'even', 'odd')  

array([['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even']], dtype='<U4')

In [108]:
np.where(h <= 7, h * 2, h / 2)  

array([[ 0. ,  2. ,  4. ],
       [ 6. ,  8. , 10. ],
       [12. , 14. ,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

### Speed Comparison

In [109]:
import random
I = 5000

In [110]:
%time mat = [[random.gauss(0, 1) for j in range(I)] \
             for i in range(I)]  

CPU times: user 6.02 s, sys: 146 ms, total: 6.17 s
Wall time: 6.17 s


In [111]:
mat[0][:5]  

[0.6430681261869718,
 0.3809847086047085,
 -2.1706694104923545,
 -1.266240260513218,
 -0.40241125408812484]

In [112]:
%time sum([sum(l) for l in mat])  

CPU times: user 67.4 ms, sys: 4.79 ms, total: 72.2 ms
Wall time: 71.3 ms


-5520.587231817743

In [113]:
import sys
sum([sys.getsizeof(l) for l in mat])  

209400000

In [114]:
%time mat = np.random.standard_normal((I, I))  

CPU times: user 514 ms, sys: 62.8 ms, total: 577 ms
Wall time: 577 ms


In [115]:
%time mat.sum()  

CPU times: user 11.2 ms, sys: 7 ms, total: 18.2 ms
Wall time: 17.1 ms


np.float64(8168.882139332722)

In [116]:
mat.nbytes  

200000000

In [117]:
sys.getsizeof(mat)  

200000128

### Structured Arrays

In [118]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'),
               ('Height', 'f'), ('Children/Pets', 'i4', 2)])  

In [119]:
dt  

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [120]:
dt = np.dtype({'names': ['Name', 'Age', 'Height', 'Children/Pets'],
             'formats':'O int float int,int'.split()})  

In [121]:
dt  

dtype([('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [122]:
s = np.array([('Smith', 45, 1.83, (0, 1)),
              ('Jones', 53, 1.72, (2, 2))], dtype=dt)  

In [123]:
s  

array([('Smith', 45, 1.83, (0, 1)), ('Jones', 53, 1.72, (2, 2))],
      dtype=[('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [124]:
type(s)  

numpy.ndarray

In [125]:
s['Name']  

array(['Smith', 'Jones'], dtype=object)

In [126]:
s['Height'].mean()  

np.float64(1.775)

In [127]:
s[0]  

np.void(('Smith', 45, 1.83, (0, 1)), dtype=[('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [128]:
s[1]['Age']  

np.int64(53)

## Vectorization of Code

In [129]:
np.random.seed(100)
r = np.arange(12).reshape((4, 3))  
s = np.arange(12).reshape((4, 3)) * 0.5  

In [130]:
r  

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [131]:
s  

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [132]:
r + s  

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [133]:
r + 3  

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [134]:
2 * r  

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [135]:
2 * r + 3  

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [136]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [137]:
r.shape

(4, 3)

In [138]:
s = np.arange(0, 12, 4)  
s  

array([0, 4, 8])

In [139]:
r + s  

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [140]:
s = np.arange(0, 12, 3)  
s  

array([0, 3, 6, 9])

In [141]:
# causes intentional error
# r + s  

In [142]:
r.transpose() + s  

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [143]:
sr = s.reshape(-1, 1)  
sr

array([[0],
       [3],
       [6],
       [9]])

In [144]:
sr.shape  

(4, 1)

In [145]:
r + s.reshape(-1, 1)  

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [146]:
def f(x):
    return 3 * x + 5  

In [147]:
f(0.5)  

6.5

In [148]:
f(r)  

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

## Memory Layout

Cf. https://eli.thegreenplace.net/2015/memory-layout-of-multi-dimensional-arrays/

In [149]:
x = np.random.standard_normal((1000000, 5))  

In [150]:
y = 2 * x + 3  

In [151]:
C = np.array((x, y), order='C')  

In [152]:
F = np.array((x, y), order='F')  

In [153]:
x = 0.0; y = 0.0  

In [154]:
C[:2].round(2)  

array([[[-1.75,  0.34,  1.15, -0.25,  0.98],
        [ 0.51,  0.22, -1.07, -0.19,  0.26],
        [-0.46,  0.44, -0.58,  0.82,  0.67],
        ...,
        [-0.05,  0.14,  0.17,  0.33,  1.39],
        [ 1.02,  0.3 , -1.23, -0.68, -0.87],
        [ 0.83, -0.73,  1.03,  0.34, -0.46]],

       [[-0.5 ,  3.69,  5.31,  2.5 ,  4.96],
        [ 4.03,  3.44,  0.86,  2.62,  3.51],
        [ 2.08,  3.87,  1.83,  4.63,  4.35],
        ...,
        [ 2.9 ,  3.28,  3.33,  3.67,  5.78],
        [ 5.04,  3.6 ,  0.54,  1.65,  1.26],
        [ 4.67,  1.54,  5.06,  3.69,  2.07]]], shape=(2, 1000000, 5))

In [155]:
%timeit C.sum()  

1.83 ms ± 25.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [156]:
%timeit F.sum()  

1.84 ms ± 28.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [157]:
%timeit C.sum(axis=0)  

6.3 ms ± 149 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [158]:
%timeit C.sum(axis=1)  

15.3 ms ± 37.5 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [159]:
%timeit F.sum(axis=0)  

31.8 ms ± 49.5 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [160]:
%timeit F.sum(axis=1)  

26.9 ms ± 22 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [161]:
F = 0.0; C = 0.0  

<img src="https://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

<a href="https://tpq.io" target="_blank">https://tpq.io</a> | <a href="https://twitter.com/dyjh" target="_blank">@dyjh</a> | <a href="mailto:training@tpq.io">training@tpq.io</a>